# Generated by Django 4.1.7 on 2023-02-23 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_remove_sensor_measurements_measurement_sensors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 15, 23, 18, 635054, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
    ]
